# Specify the dependencies to be placed into spec/fixtures/modules when
# rake spec or rake spec_prep is run. See
# https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures
fixtures:
  repositories:
    # Grab stdlib from git (not needed as it should be in our puppet repo)
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    staging: https://github.com/nanliu/puppet-staging
  symlinks:
    # Create a link from spec/fixtures/modules/<module_name> to this directory so
    # puppet's manifest loader will see the correct path including the module
    # name
    heka: "#{source_dir}"
